server:
  port: 9000

spring:
  application:
    name: latte-portal
  thymeleaf:
    cache: false
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/workplace?characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
#  mvc:
#    static-path-pattern: /**
